# Generated by Django 4.0.6 on 2022-07-30 12:58

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('icon', models.CharField(choices=[('icofont-simple-smile', 'smiley-face'), ('icofont-document-folder', 'document-folder'), ('icofont-live-support', 'live-support'), ('icofont-users-alt-5', 'users'), ('icofont-water-drop', 'water-drop')], default='icofont-water-drop', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=website.models.icon_image_directory)),
                ('linked_in', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
