# Generated by Django 4.0.6 on 2022-08-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_service_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='other_name',
        ),
        migrations.AddField(
            model_name='teammember',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
