# Generated by Django 4.0.6 on 2022-10-11 18:41

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='hello', upload_to=website.models.icon_image_directory),
            preserve_default=False,
        ),
    ]
