# Generated by Django 4.0.6 on 2022-10-11 23:02

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=website.models.product_image_directory),
        ),
    ]
