# Generated by Django 4.0.6 on 2022-08-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_teammember_other_name_teammember_other_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='ProductFeature',
        ),
    ]
