# Generated by Django 4.0.6 on 2022-08-14 19:25

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_feature_productfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('customer_phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
