# Generated by Django 4.0.6 on 2022-08-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model_features', to='website.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.basket')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.basket')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is a product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='icon',
            field=models.CharField(choices=[('icofont-simple-smile', 'smiley-face'), ('icofont-document-folder', 'document-folder'), ('icofont-live-support', 'live-support'), ('icofont-users-alt-5', 'users'), ('icofont-water-drop', 'single water drop'), ('icofont-energy-water', 'energy'), ('fa fa-faucet-drip', 'drop of water from tap')], default='icofont-water-drop', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('icofont-simple-smile', 'smiley-face'), ('icofont-document-folder', 'document-folder'), ('icofont-live-support', 'live-support'), ('icofont-users-alt-5', 'users'), ('icofont-water-drop', 'single water drop'), ('icofont-energy-water', 'energy'), ('fa fa-faucet-drip', 'drop of water from tap')], default='icofont-water-drop', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.service'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='website.product'),
        ),
    ]
