# Generated by Django 4.0.6 on 2022-08-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_productmodel_productmodelfeature_productorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.basket'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.basket'),
        ),
    ]
